### PR TITLE
Use haskeline in create script

### LINKED ISSUE #499: Use haskeline for create-message-template.hs
I noticed I cannot use my arrow keys to move the cursor when creating a new message. Delete also doesn't work properly over multiple lines.

The https://hackage.haskell.org/package/haskeline package provides a solution for these problems.

### PR DESCRIPTION
**Pull request by BinderDavid**
Fixes #499 

Uses `haskeline` to allow easier line-editing when using the `create-message-template.hs` script.

### CODE REVIEW

**Comment by BinderDavid** [comment]
@noughtmare Can you take a look and verify that it works as intended?

**Comment by noughtmare** [comment]
It might be good to add constraints to the dependencies (at least lower bounds).

File: message-index/create-message-template.hs [hunk 1]
```diff
@@ -141,23 +141,21 @@ validateExampleName "" = False
...
+readExample :: Int -> ToolM String
 readExample i = do
-  putStrLn ""
-  putStrLn ("· Give a name for example " <> show i)
-  putStrLn "The name should not contain spaces and begin with a lowercase letter."
-  putStr "Input: "
-  ln <- getLine
+  outputStrLn ""
+  outputStrLn ("· Give a name for example " <> show i)
+  outputStrLn "The name should not contain spaces and begin with a lowercase letter."
```
Comment (jhrcek) [inline message-index/create-message-template.hs:157]: While you're updating this, could you please reword the promt for better clarify?

Yesterday I wasn't sure if it means this:
The name should not ( contain spaces and begin with a lowercase letter ).

or this:

The name should ( not contain spaces ) and (shoud) begin with a lowercase letter.
:smile: 

How about:
```suggestion
  outputStrLn "The name should not contain spaces and should begin with a lowercase letter."
```

**Review by jhrcek — APPROVED** [review]
Nice improvement :+1: . Just a small suggestion for one prompt that confused me yesterday.
